language: c
sudo: false # only for faster builds
script:
  - g++ -o prueba -fprofile-arcs -ftest-coverage main.c
  - ./prueba
  - gcov main.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
